// cms/sveltekit/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { PUBLIC_SITE_URL } from '$env/static/public';
	import DirectusImage from '$lib/components/shared/DirectusImage.svelte';
	import Container from '$lib/components/ui/Container.svelte';
	import Headline from '$lib/components/ui/Headline.svelte';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import type { PageData } from './$types';
	import BaseText from '$lib/components/ui/Text.svelte';
	import ShareDialog from '$lib/components/ui/ShareDialog.svelte';
	import setAttr from '$lib/directus/visualEditing';

	let { data }: { data: PageData } = $props();

	let post = $derived(data.post);
	const author = $derived(data.author);
	const authorName = $derived([author?.first_name, author?.last_name].filter(Boolean).join(' '));
	const postUrl = `${PUBLIC_SITE_URL}/blog/${page.params.slug}`;
</script>

<Container class="py-12">
	{#if post?.image}
		<div class="mb-8">
			<div
				class="relative h-[400px] w-full overflow-hidden rounded-lg"
				data-directus={setAttr({
					collection: 'posts',
					item: post.id,
					fields: ['image', 'meta_header_image'],
					mode: 'modal'
				})}
			>
				<DirectusImage
					uuid={post.image as string}
					alt={post.title || 'post header image'}
					class="object-cover"
					fill
					sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 1200px"
				/>
			</div>
		</div>
	{/if}
	<Headline
		as="h2"
		headline={post.title}
		class="mb-4 text-accent!"
		data-directus={setAttr({
			collection: 'posts',
			item: post.id,
			fields: ['title', 'slug'],
			mode: 'popover'
		})}
	/>
	<Separator class="mb-8" />

	<div class="grid grid-cols-1 gap-12 lg:grid-cols-[minmax(0,2fr)_400px]">
		<main class="text-left">
			<BaseText
				content={post.content || ''}
				data-directus={setAttr({
					collection: 'posts',
					item: post.id,
					fields: ['content', 'meta_header_content'],
					mode: 'drawer'
				})}
			/>
		</main>

		<aside class="h-fit max-w-[496px] space-y-6 rounded-lg bg-background-muted p-6">
			{#if author}
				<div
					class="flex items-center space-x-4"
					data-directus={setAttr({
						collection: 'posts',
						item: post.id,
						fields: ['author'],
						mode: 'popover'
					})}
				>
					{#if author.avatar}
						<DirectusImage
							uuid={author.avatar as string}
							alt={authorName || 'author avatar'}
							class="size-[48px] rounded-full object-cover"
							width={48}
							height={48}
						/>
					{/if}
					<div>
						{#if authorName}
							<p
								class="font-bold"
								data-directus={setAttr({
									collection: 'posts',
									item: post.id,
									fields: ['author'],
									mode: 'popover'
								})}
							>
								{authorName}
							</p>
						{/if}
					</div>
				</div>
			{/if}

			{#if post.description}
				<p
					data-directus={setAttr({
						collection: 'posts',
						item: post.id,
						fields: 'description',
						mode: 'popover'
					})}
				>
					{post.description}
				</p>
			{/if}

			<div class="flex justify-start">
				<ShareDialog {postUrl} postTitle={post.title} />
			</div>

			<div>
				<Separator class="my-4" />
				<h3 class="mb-4 font-bold">Related Posts</h3>
				<div class="space-y-4">
					{#each data.relatedPosts as relatedPost (relatedPost.id)}
						<a
							href={`/blog/${relatedPost.slug}`}
							class="group flex items-center space-x-4 hover:text-accent"
						>
							{#if relatedPost.image}
								<div class="relative h-[100px] w-[150px] shrink-0 overflow-hidden rounded-lg">
									<DirectusImage
										uuid={relatedPost.image as string}
										alt={relatedPost.title || 'related posts'}
										class="object-cover transition-transform duration-300 group-hover:scale-110"
										fill
										sizes="(max-width: 768px) 100px, (max-width: 1024px) 150px, 150px"
									/>
								</div>
							{/if}
							<span class="font-heading">{relatedPost.title}</span>
						</a>
					{/each}
				</div>
			</div>
		</aside>
	</div>
</Container>

// simple-cms/nextjs/src/app/blog/[slug]/page.tsx
import { fetchPostBySlug, fetchRelatedPosts, fetchAuthorById } from '@/lib/directus/fetchers';
import { draftMode } from 'next/headers';
import DirectusImage from '@/components/shared/DirectusImage';
import BaseText from '@/components/ui/Text';
import { Separator } from '@/components/ui/separator';
import ShareDialog from '@/components/ui/ShareDialog';
import Link from 'next/link';
import Headline from '@/components/ui/Headline';
import Container from '@/components/ui/container';
import { getDirectusAssetURL } from '@/lib/directus/directus-utils';
import AdminBar from '@/components/shared/AdminBar';

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
	const { slug } = await params;

	try {
		const post = await fetchPostBySlug(slug);

		if (!post) {
			return;
		}

		const ogImage = post.image ? getDirectusAssetURL(post.image) : null;

		return {
			title: post?.seo?.title ?? post.title ?? '',
			description: post?.seo?.meta_description ?? '',
			openGraph: {
				title: post?.seo?.title ?? post.title ?? '',
				description: post?.seo?.meta_description ?? '',
				url: `${process.env.NEXT_PUBLIC_SITE_URL}/blog/${slug}`,
				type: 'article',
				images: ogImage ? [{ url: ogImage }] : undefined,
			},
		};
	} catch (error) {
		console.error('Error loading post metadata:', error);

		return;
	}
}

export default async function BlogPost({ params }: { params: Promise<{ slug: string }> }) {
	const { isEnabled } = await draftMode();
	const { slug } = await params;

	let post;
	try {
		post = await fetchPostBySlug(slug);
	} catch (error) {
		console.error('Error loading post:', error);

		return;
	}

	if (!post) {
		return <div className="text-center text-xl mt-[20%]">404 - Post Not Found</div>;
	}
	const relatedPosts = await fetchRelatedPosts(post.id);
	const author = post.author ? await fetchAuthorById(post.author as string) : null;

	const authorName = [author?.first_name, author?.last_name].filter(Boolean).join(' ');
	const postUrl = `${process.env.NEXT_PUBLIC_SITE_URL}/blog/${slug}`;

	return (
		<>
			{isEnabled && <p>(Draft Mode)</p>}
			{!isEnabled && <AdminBar contentId={post.id} type="post" />}
			<Container className="py-12">
				{post.image && (
					<div className="mb-8">
						<div className="relative w-full h-[400px] overflow-hidden rounded-lg">
							<DirectusImage
								uuid={post.image as string}
								alt={post.title || 'post header image'}
								className="object-cover"
								fill
								sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 1200px"
							/>
						</div>
					</div>
				)}

				<Headline as="h2" headline={post.title} className="!text-accent mb-4" />
				<Separator className="mb-8" />

				<div className="grid grid-cols-1 lg:grid-cols-[minmax(0,_2fr)_400px] gap-12">
					<main className="text-left">
						<BaseText content={post.content || ''} />
					</main>

					<aside className="space-y-6 p-6 rounded-lg max-w-[496px] h-fit bg-background-muted">
						{author && (
							<div className="flex items-center space-x-4">
								{author.avatar && (
									<DirectusImage
										uuid={author.avatar as string}
										alt={authorName || 'author avatar'}
										className="rounded-full object-cover size-[48px]"
										width={48}
										height={48}
									/>
								)}
								<div>{authorName && <p className="font-bold">{authorName}</p>}</div>
							</div>
						)}

						{post.description && <p className="">{post.description}</p>}

						<div className="flex justify-start">
							<ShareDialog postUrl={postUrl} postTitle={post.title} />
						</div>

						<div>
							<Separator className="my-4" />
							<h3 className="font-bold mb-4">Related Posts</h3>
							<div className="space-y-4">
								{relatedPosts.map((relatedPost) => (
									<Link
										key={relatedPost.id}
										href={`/blog/${relatedPost.slug}`}
										className="flex items-center space-x-4 hover:text-accent group"
									>
										{relatedPost.image && (
											<div className="relative shrink-0 w-[150px] h-[100px] overflow-hidden rounded-lg">
												<DirectusImage
													uuid={relatedPost.image as string}
													alt={relatedPost.title || 'related posts'}
													className="object-cover transition-transform duration-300 group-hover:scale-110"
													fill
													sizes="(max-width: 768px) 100px, (max-width: 1024px) 150px, 150px"
												/>
											</div>
										)}
										<span className="font-heading">{relatedPost.title}</span>
									</Link>
								))}
							</div>
						</div>
					</aside>
				</div>
			</Container>
		</>
	);
}
