// cms/astro/src/components/layout/NavigationBar.tsx
'use client';

import { useEffect, useState } from 'react';
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuLink,
  NavigationMenuViewport,
} from '@/components/ui/navigation-menu';
import { DropdownMenu, DropdownMenuContent, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { ChevronDown, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Container from '@/components/ui/Container';
import SearchModal from '@/components/ui/SearchModal';
import ThemeToggle from '@/components/ui/ThemeToggle';
import { forwardRef } from 'react';
import { setAttr } from '@directus/visual-editing';

interface NavigationBarProps {
  navigation: {
    id: string;
    items: {
      id: string;
      title: string;
      url?: string;
      page?: { permalink: string };
      children?: {
        id: string;
        title: string;
        url?: string;
        page?: { permalink: string };
      }[];
    }[];
  };
  globals: {
    logo?: string;
    logo_dark_mode?: string;
  };
}

const NavigationBar = forwardRef<HTMLElement, NavigationBarProps>(({ navigation, globals }, ref) => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({});
  const directusURL = import.meta.env.PUBLIC_DIRECTUS_URL;

  const lightLogoUrl = globals?.logo ? `${directusURL}/assets/${globals.logo}` : '/images/logo.svg';
  const darkLogoUrl = globals?.logo_dark_mode ? `${directusURL}/assets/${globals.logo_dark_mode}` : '';

  const handleLinkClick = () => {
    setMobileMenuOpen(false);
  };

  const toggleSection = (id: string) => {
    setOpenSections((prev) => ({
      ...prev,
      [id]: !prev[id],
    }));
  };

  // Close mobile menu on window resize or navigation
  useEffect(() => {
    const handleResize = () => setMobileMenuOpen(false);
    const handleRouteChange = () => setMobileMenuOpen(false);
    window.addEventListener('resize', handleResize);
    window.addEventListener('popstate', handleRouteChange);

    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('popstate', handleRouteChange);
    };
  }, []);

  return (
    <header ref={ref} className="sticky top-0 z-50 w-full bg-background text-foreground">
      <Container className="flex items-center justify-between p-4">
        <a href="/" className="shrink-0">
          <img src={lightLogoUrl} alt="Logo" className="w-[120px] h-auto dark:hidden" />
          {darkLogoUrl && <img src={darkLogoUrl} alt="Dark Logo" className="w-[120px] h-auto hidden dark:block" />}
        </a>
        <nav className="flex items-center gap-4">
          <SearchModal />
          <NavigationMenu
            className="hidden md:flex"
            data-directus={
              navigation
                ? setAttr({
                    collection: 'navigation',
                    item: navigation.id,
                    fields: ['items'],
                    mode: 'modal',
                  })
                : undefined
            }
          >
            <NavigationMenuList className="flex gap-6">
              {navigation?.items?.map((section) => (
                <NavigationMenuItem key={section.id}>
                  {section.children?.length ? (
                    <>
                      <NavigationMenuTrigger className="font-heading text-nav focus:outline-hidden">
                        <span className="font-heading text-nav">{section.title}</span>
                      </NavigationMenuTrigger>
                      <NavigationMenuContent className="bg-background">
                        <ul className="flex flex-col gap-2 p-4 w-[200px] bg-popover">
                          {section.children.map((child) => (
                            <li key={child.id}>
                              <NavigationMenuLink
                                href={child.page?.permalink || child.url || '#'}
                                className="font-heading text-nav block w-full p-2 rounded-md hover:text-accent"
                              >
                                {child.title}
                              </NavigationMenuLink>
                            </li>
                          ))}
                        </ul>
                      </NavigationMenuContent>
                    </>
                  ) : (
                    <NavigationMenuLink
                      href={section.page?.permalink || section.url || '#'}
                      className="font-heading text-nav"
                    >
                      {section.title}
                    </NavigationMenuLink>
                  )}
                </NavigationMenuItem>
              ))}
            </NavigationMenuList>
            <NavigationMenuViewport />
          </NavigationMenu>

          {/* Mobile menu */}
          <div className="flex md:hidden">
            <DropdownMenu open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  aria-label="Open menu"
                  className="dark:text-white dark:hover:text-accent"
                >
                  <Menu className="h-5 w-5" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                align="start"
                className="top-full w-screen max-w-full p-6 shadow-md bg-background z-50"
              >
                <div className="flex flex-col gap-4">
                  {navigation?.items?.map((section) => (
                    <div key={section.id}>
                      {section.children?.length ? (
                        <Collapsible open={openSections[section.id]} onOpenChange={() => toggleSection(section.id)}>
                          <CollapsibleTrigger className="flex items-center justify-between w-full font-heading text-nav hover:text-accent">
                            <span>{section.title}</span>
                            <ChevronDown
                              className={`h-4 w-4 transition-transform duration-200 ${
                                openSections[section.id] ? 'rotate-180' : ''
                              }`}
                            />
                          </CollapsibleTrigger>
                          <CollapsibleContent className="ml-4 mt-2 flex flex-col gap-2">
                            {section.children.map((child) => (
                              <a
                                key={child.id}
                                href={child.page?.permalink || child.url || '#'}
                                className="font-heading text-nav"
                                onClick={handleLinkClick}
                              >
                                {child.title}
                              </a>
                            ))}
                          </CollapsibleContent>
                        </Collapsible>
                      ) : (
                        <a
                          href={section.page?.permalink || section.url || '#'}
                          className="font-heading text-nav"
                          onClick={handleLinkClick}
                        >
                          {section.title}
                        </a>
                      )}
                    </div>
                  ))}
                </div>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          <ThemeToggle />
        </nav>
      </Container>
    </header>
  );
});

NavigationBar.displayName = 'NavigationBar';
export default NavigationBar;

// cms/nuxt/app/components/NavigationBar.vue
<script setup lang="ts">
import { Menu, ChevronDown } from 'lucide-vue-next';
import SearchModal from '~/components/base/SearchModel.vue';

interface NavigationItem {
	id: string;
	title: string;
	url?: string;
	page?: { permalink: string };
	children?: NavigationItem[];
}

// Using template ref to expose the navigation bar to the layout for visual editing
const navigationRef = useTemplateRef('navigationRef');
defineExpose({ navigationRef });

interface Navigation {
	items: NavigationItem[];
}

interface Globals {
	logo?: string;
	logo_dark_mode?: string;
}

const props = defineProps<{
	navigation: Navigation;
	globals: Globals;
}>();

const menuOpen = ref(false);
const runtimeConfig = useRuntimeConfig();
const { setAttr } = useVisualEditing();

const lightLogoUrl = computed(() =>
	props.globals?.logo ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo}` : '/images/logo.svg',
);

const darkLogoUrl = computed(() =>
	props.globals?.logo_dark_mode ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo_dark_mode}` : '',
);

const handleLinkClick = () => {
	menuOpen.value = false;
};
</script>

<template>
	<header ref="navigationRef" class="sticky top-0 z-50 w-full bg-background text-foreground">
		<Container class="flex items-center justify-between p-4">
			<NuxtLink to="/" class="shrink-0">
				<img :src="lightLogoUrl" alt="Logo" class="w-[120px] h-auto dark:hidden" width="150" height="100" />
				<img
					v-if="darkLogoUrl"
					:src="darkLogoUrl"
					alt="Logo (Dark Mode)"
					class="w-[120px] h-auto hidden dark:block"
					width="150"
					height="100"
				/>
			</NuxtLink>

			<nav class="flex items-center gap-4">
				<SearchModal />
				<NavigationMenu
					class="hidden md:flex"
					:data-directus="
						setAttr({ collection: 'navigation', item: props.navigation.id, fields: ['items'], mode: 'modal' })
					"
				>
					<NavigationMenuList class="flex gap-6">
						<NavigationMenuItem v-for="section in props.navigation.items" :key="section.id">
							<template v-if="section.children?.length">
								<NavigationMenuTrigger
									class="focus:outline-hidden font-heading text-nav! hover:bg-background hover:text-accent"
								>
									{{ section.title }}
								</NavigationMenuTrigger>
								<NavigationMenuContent class="min-w-[200px] rounded-md bg-background p-4 shadow-md">
									<ul class="min-h-[100px] flex flex-col gap-2">
										<li v-for="child in section.children" :key="child.id">
											<NavigationMenuLink as-child>
												<NuxtLink :to="child.page?.permalink || child.url || '#'" class="font-heading text-nav">
													{{ child.title }}
												</NuxtLink>
											</NavigationMenuLink>
										</li>
									</ul>
								</NavigationMenuContent>
							</template>

							<NavigationMenuLink v-else as-child>
								<NuxtLink :to="section.page?.permalink || section.url || '#'" class="font-heading text-nav p-2">
									{{ section.title }}
								</NuxtLink>
							</NavigationMenuLink>
						</NavigationMenuItem>
					</NavigationMenuList>
				</NavigationMenu>

				<div class="flex md:hidden">
					<DropdownMenu v-model:open="menuOpen">
						<DropdownMenuTrigger as-child>
							<Button
								variant="link"
								size="icon"
								aria-label="Open menu"
								class="text-black dark:text-white dark:hover:text-accent"
							>
								<Menu />
							</Button>
						</DropdownMenuTrigger>

						<DropdownMenuContent
							align="start"
							class="top-full w-screen p-6 shadow-md max-w-full overflow-hidden bg-background"
						>
							<div class="flex flex-col gap-4">
								<div v-for="section in props.navigation.items" :key="section.id">
									<Collapsible v-if="section.children?.length">
										<CollapsibleTrigger
											class="font-heading text-nav hover:text-accent w-full text-left flex items-center focus:outline-hidden"
										>
											<span>{{ section.title }}</span>
											<ChevronDown class="size-4 ml-1 hover:rotate-180 active:rotate-180 focus:rotate-180" />
										</CollapsibleTrigger>
										<CollapsibleContent class="ml-4 mt-2 flex flex-col gap-2">
											<NuxtLink
												v-for="child in section.children"
												:key="child.id"
												:to="child.page?.permalink || child.url || '#'"
												class="font-heading text-nav"
												@click="handleLinkClick"
											>
												{{ child.title }}
											</NuxtLink>
										</CollapsibleContent>
									</Collapsible>

									<NuxtLink
										v-else
										:to="section.page?.permalink || section.url || '#'"
										class="font-heading text-nav"
										@click="handleLinkClick"
									>
										{{ section.title }}
									</NuxtLink>
								</div>
							</div>
						</DropdownMenuContent>
					</DropdownMenu>
				</div>

				<ThemeToggle />
			</nav>
		</Container>
	</header>
</template>
